apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-dfwh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-dfwh
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-dfwh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-dfwh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-dfwh
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jpsx-tenant/rhtap-demo-app/hacbs-test-project-dfwh@sha256:72e09846f7db43c1c60fd906e754b6db130a3ff86ed4a6f04ca0db775e7de3d6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
